- src/Altinn.Notifications/appsettings.json
Pods fail on startup in AT due to the migration folder not being found. Fixed value in appsettings to reflect actual path for migration folder in docker container.
> fix migration folder path in appsettings

- src/Altinn.Notifications.Core/Models/NotificationTemplate/EmailTemplate.cs
- src/Altinn.Notifications/Models/EmailNotificationOrderRequestExt.cs
- src/Altinn.Notifications/Validators/EmailNotificationOrderRequestValidator.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
Optional for end user to provide from address, default will be used if nothing is provided
- #246
> from address optional to provide

- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- src/Altinn.Notifications/Models/OrderIdExt.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/PostTests.cs
Using a json object to return the created order id on post of notification order request
- #247
> return object on post of order

- src/Altinn.Notifications/Altinn.Notifications.csproj
- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- src/Altinn.Notifications/Controllers/OrdersController.cs
- src/Altinn.Notifications/Program.cs
Ensuring response headers are documented in swagger as well as all xml comments and response code descriptions. 
N/A
> ensuring more detailed swagger

- src/Altinn.Notifications/Mappers/OrderMapper.cs
- src/Altinn.Notifications/Models/EmailNotificationOrderRequestExt.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/PostTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
From address is no longer included in the email notification order request external model. 
Default from address will be used for all email notifications for now. 
- #264
> removed from address prop from ext model

- src/Altinn.Notifications.Persistence/Migration/v0.08/01-setup-functions.sql
Edited existing release, will run script manually in AT envs to save number of migration version. 
1 minute makes more sense wr.t. to the schedule of the cron-jobs. 
- #262
> adjust grace period to 1 min

- src/Altinn.Notifications.Persistence/Health/PostgresHealthCheck.cs
- src/Altinn.Notifications/Program.cs
Disabling Kafka health check while we investigate what is causing the instability in the health check.
- N/A
> Disable kafka health check

- .github/workflows/build-and-analyze.yml
- .github/workflows/codeql-analysis.yml
- Dockerfile
- src/Altinn.Notifications.Core/Altinn.Notifications.Core.csproj
- src/Altinn.Notifications.Integrations/Altinn.Notifications.Integrations.csproj
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications/Altinn.Notifications.csproj
- test/Altinn.Notifications.IntegrationTests/Altinn.Notifications.IntegrationTests.csproj
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
Upgraded application to .NET 8 
- #N/A
> Upgraded to .NET 8

- src/Altinn.Notifications/Mappers/OrderMapper.cs
- src/Altinn.Notifications/Validators/EmailNotificationOrderRequestValidator.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
Validating `requestedSendTime` to check if it has zone specified or not.
Introduced a method name `HasTimeZone` in the `EmailNotificationOrderRequestValidator` validator and implemented validator with this method. If the zone isn't specified then it'll throw a 400 HTTP error.
- FIX #275
> Validating `requestedSendTime` to check if it has zone specified or not

- src/Altinn.Notifications.Core/Services/GetOrderService.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetWithStatusById.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/GetOrderServiceTests.cs
Same puctuation for all order status descriptions.
- N/A
> added missing '.'

- src/Altinn.Notifications.Core/Configuration/NotificationOrderConfig.cs
- src/Altinn.Notifications.Core/Enums/NotificationChannel.cs
- src/Altinn.Notifications.Core/Enums/NotificationTemplateType.cs
- src/Altinn.Notifications.Core/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Core/Models/NotificationTemplate/INotificationTemplate.cs
- src/Altinn.Notifications.Core/Models/NotificationTemplate/SmsTemplate.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IOrderRequestService.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
This PR is made to implement the core logic for placing an sms notification order described on the issue #336 
- Added SMS channel to `NotificationChannel` enum.
- Added SMS notification template type to the `NotificationTemplateType` enum.
- Added SMS template(`SmsTemplate`) to the `NotificationTemplate` directory.
- Added JSON subtype(`JsonDerivedType`) for SMS in the notification interface.
- Renamed `EmailNotificationOrderService` and `IEmailNotificationOrderService` to `OrderRequestService` and `IOrderRequestService`.
- Renamed `RegisterEmailNotificationOrder` in `OrderRequestService` to `RegisterNotificationOrder`.
- Added default sender number in the config
- Extended method for setting default value when empty
- Necessary unit tests added
- No manual QA would be done as mentioned …
> #336 Implementation of core logic for placing an sms notification order

- .github/workflows/regression-test-AT22.yaml
- .github/workflows/regression-test-AT23.yaml
- .github/workflows/regression-test-AT24.yaml
- .github/workflows/regression-test-ATX.yaml
Seperate workflow per AT environment calling the same common script
- #339
> #339 seperate regression test workflow per env

- src/Altinn.Notifications.Core/Services/GetOrderService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IGetOrderService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/INotificationSummaryService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IOrderRequestService.cs
- src/Altinn.Notifications.Core/Services/NotificationSummaryService.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications.Core/Shared/Result.cs
- src/Altinn.Notifications.Core/Shared/ServiceError.cs
- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- src/Altinn.Notifications/Controllers/EmailNotificationsController.cs
- src/Altinn.Notifications/Controllers/OrdersController.cs
- src/Altinn.Notifications/Controllers/SmsNotificationOrdersController.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsController/EmailNotificationsControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/OrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/SmsNotificationsOrdersController/SmsNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/GetOrderServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
Removed use of tuples to return success or error response.
> Using Result instead of tuple where applicable

- src/Altinn.Notifications/Extensions/ResourceLinkExtensions.cs
- src/Altinn.Notifications/Models/NotificationChannelExt.cs
- src/Altinn.Notifications/Models/OrderResourceLinksExt.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetByIdTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
- The /notifications  endpoint for orders has never been implemented and should not be exposed in the self links of an order
- Added missing enum type to src/Altinn.Notifications/Models/NotificationChannelExt.cs
- #N/A
> removed self link for oerd/{id}/notifications endpoint

- src/Altinn.Notifications.Core/Models/Notification/SmsSendOperationResult.cs
- src/Altinn.Notifications.Core/Persistence/ISmsNotificationRepository.cs
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/SmsSendOperationResultTests.cs
When delivery reports are returned for sms, the notificationId is not available, hence it should be possible to update the database with only the gateway reference
- #361
> option to update sms send status with only gateway ref

- Dockerfile
Telemetry features need a folder for temporary storage of data when there are network issues. This is missing for notifications.
- Discovered when analyzing an issue in production.
> Create /tmp/logtelemetry during build

- src/Altinn.Notifications.Persistence/Migration/v0.25/01-alter-procedures.sql
- src/Altinn.Notifications.Persistence/Migration/v0.25/02-alter-functions.sql
- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Utils/TestdataUtil.cs
In preparation of removing the recipientId property we need to stop using the column in the table e.g. on creation on new notifications. 
- #436
> ignoring recipientId in all db read and writes

- src/Altinn.Notifications.Core/Persistence/ISmsNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/Interfaces/ISmsNotificationService.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Core/Services/SmsOrderProcessingService.cs
- src/Altinn.Notifications.Persistence/Migration/v0.27/01-alter-procedure.sql
- src/Altinn.Notifications.Persistence/Migration/v0.27/02-alter-functions.sql
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/PostgreUtil.cs
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsOrderProcessingServiceTests.cs
- Calculating sms count based of concatination rules from Link Mobility on notification creation
- Updated metrics function to use sms count column to set number of sms for service owner
- #440
> Calculating sms count based of text lenght and returning number for metrics

- src/Altinn.Notifications.Core/Enums/EmailNotificationResultType.cs
- src/Altinn.Notifications.Core/Models/Notification/EmailSendOperationResult.cs
- src/Altinn.Notifications.Core/Persistence/IEmailNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/EmailNotificationSummaryService.cs
- src/Altinn.Notifications.Persistence/Migration/v0.28/01-alter-types.sql
- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/EmailNotificationRepositoryTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/PostgreUtil.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/EmailNotificationSummaryServiceTests.cs
- Updated db enum to reflect values for send result for email and sms
- Fixed repository logic to update send result for email with/without notification id and operationid
- Added integration tests 
- #281
> Support for registering email delivery report result

- src/Altinn.Notifications.Core/Models/Notification/EmailSendOperationResult.cs
Bug fix for deserialization of email send operation result. Notification id optional, so should check on multiple properties
> check on id or operationId defined

- src/Altinn.Notifications.Core/Models/Recipient.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/RecipientTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
- Fixed bug where national identity number is persisted in db on the generated notification
- Changed implementation to ensure that intial lookup of contact details & reservation is not persisted to the notification order in db. 
Merging this PR will result in reservation status being made available for TE in order request response, and through orders/{id}/notifications/sms endpoint. 
- The orders/{id} returns original order without reserve status or contact details. Should this endpoint rather check if notifications have been generated and merge the original order with the recipient data we used when actually sending the notification? How would this look for an org, where a single order recipient results in multiple notification recipients? 
- #439
> #439 only persist national identity number on notification

- src/Altinn.Notifications.Core/Models/Orders/NotificationOrder.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/OrdersControllerTests.cs
Bug fix for persisting ignoreReservations 
- #439
> including ignorereservations when creating order in service

- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
Fix for recipient organization number not being persisted for generated notifications
- #456
> ensuring recipient org number is persisted to notification

- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
Optimizing the code. Currently all recipients are deep copied when completing initial lookup, this is only needed for the users that will be looked up. 
- N/A
> only copy recipient if lookup is required

- src/Altinn.Notifications.Core/Services/EmailNotificationService.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/EmailNotificationServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
Fixed bug where only first address point was used to generate notifications for a recipient. 
- #456
> Ensure all address points get a notification

- src/Altinn.Notifications/Validators/EmailNotificationOrderRequestValidator.cs
- src/Altinn.Notifications/Validators/SmsNotificationOrderRequestValidator.cs
- src/Altinn.Notifications/Validators/ValidationConstants.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/SmsNotificationOrderRequestValidatorTests.cs
Validation of digits and length when organization number or national identity number is provided for recipient. 
- #536
> added basic validation of recipient nin and orgno

- src/Altinn.Notifications.Core/Integrations/IConditionClient.cs
- src/Altinn.Notifications.Core/Models/SendCondition/ConditionClientError.cs
- src/Altinn.Notifications.Integrations/Altinn.Notifications.Integrations.csproj
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/SendCondition/SendConditionClient.cs
- src/Altinn.Notifications.Integrations/SendCondition/SendConditionResponse.cs
- src/Altinn.Notifications/Controllers/SendConditionController.cs
- src/Altinn.Notifications/appsettings.Development.json
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.Tests/Notifications.Integrations/SendCondition/SendConditionClientTests.cs
> Implemented condition client logic

- src/Altinn.Notifications.Core/Enums/NotificationChannel.cs
- src/Altinn.Notifications.Core/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Core/Services/ContactPointService.cs
- src/Altinn.Notifications.Core/Services/EmailOrderProcessingService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IContactPointService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IEmailOrderProcessingService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IPreferredChannelProcessingService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/ISmsOrderProcessingService.cs
- src/Altinn.Notifications.Core/Services/OrderProcessingService.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications.Core/Services/PreferredChannelProcessingService.cs
- src/Altinn.Notifications.Core/Services/SmsOrderProcessingService.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/ContactPointServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderProcessingServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/PreferredChannelProcessingServiceTests.cs
> Email and SmsPreferred support in Altinn.Notifications.Core

- src/Altinn.Notifications/Mappers/OrderMapper.cs
- src/Altinn.Notifications/Models/NotificationOrderRequestResponseExt.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
This bugfix corrects the handling of recipients when ordering notifications for only mobile phone numbers.
Now, SmsAddressPoints are created and added for recipients when mapping `NotificationOrderRequestExt `-> `NotificationOrderRequest `in _src\Altinn.Notifications\Mappers\OrderMapper.cs_.
One of the tests in `OrderMapperTests` have been extended with a "mobile no. only" recipient. This gives test coverage of the scenario where this mapping previously has failed.
- #608
> Add SMS address point in NotificationOrderRequest for recipients with only phone no. 

- README.md
Updates the instruction for running Notifications locally, using the up-to-date path to the startup project
- N/A
> Correct the path to startup project in README

- src/Altinn.Notifications.Core/Helpers/MobileNumberHelper.cs
- src/Altinn.Notifications/Validators/Rules/RecipientRules.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/NotificationOrderRequestValidatorTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/SmsNotificationOrderRequestValidatorTests.cs
When placing notification orders where SMS is involved, mobile numbers that include invalid characters (like letters) now produces response code 400 instead of 500. Additionally, the general response for such invalid numbers is changed:
- Before: "_Invalid mobile number format_".
- Now: "_Mobile number can contain only '+' and numeric characters, and it must adhere to the E.164 standard._"
Affected endpoints:
- POST /notifications/api/v1/orders/sms
- POST /notifications/api/v1/orders
The `MobileNumberHelper` class, used by Validators to perform number validation, now has a try/catch for when PhoneNumberUtil throws NumberParseException. These exceptions now result in the method `IsValidMobileNumber` returning `false`.
- #619
> Improved handling of invalid mobile numbers

- src/Altinn.Notifications.Core/Services/EmailOrderProcessingService.cs
- src/Altinn.Notifications.Core/Services/KeywordsService.cs
- src/Altinn.Notifications.Core/Services/SmsOrderProcessingService.cs
After merging the changes for #545, some regression tests failed because the Notification API was trying to retrieve data from the Register API unnecessarily. This PR fixes the issue by ensuring the Register API only retrieves data for entries that have at least one keyword and either a valid national identity number or organization number.
- #545
> Restrict data retrieval from the Register API

- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
Fix for recipient organization number not being persisted for generated Sms notifications
Similar to https://github.com/Altinn/altinn-notifications/pull/515
- #705
> Persist recipient orgNo for sms notifications

- src/Altinn.Notifications.Core/Altinn.Notifications.Core.csproj
- src/Altinn.Notifications.Core/Enums/SmsNotificationResultType.cs
- src/Altinn.Notifications.Core/Models/Notification/INotification.cs
- src/Altinn.Notifications.Core/Models/Notification/NotificationResult.cs
- src/Altinn.Notifications.Core/Models/Notification/SmsNotification.cs
- src/Altinn.Notifications.Core/Models/Notification/SmsSendOperationResult.cs
- src/Altinn.Notifications.Core/Models/Recipients/SmsRecipient.cs
- src/Altinn.Notifications.Core/Models/Sms.cs
- src/Altinn.Notifications.Core/Persistence/ISmsNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/Interfaces/ISmsNotificationService.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- src/Altinn.Notifications/Altinn.Notifications.csproj
- test/Altinn.Notifications.IntegrationTests/Altinn.Notifications.IntegrationTests.csproj
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/SmsStatusConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/SmsSendOperationResultTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
Remove the `or` operator that was used to update the SMS order status based on the gateway reference.
- #700
> Do not update the SMS order based on the gateway reference.

- src/Altinn.Notifications.Core/Models/Sms.cs
- src/Altinn.Notifications.Core/Persistence/ISmsNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
The previous Notifications API used an or operator to find out which row to update. This query is divide into two quires to make sure we update the data when we have valid identifier.
- #700
> Split a data update query into two separate queries

- .github/workflows/build-and-analyze.yml
Remove the superfluous caching of Sonar packages in the build pipeline.
[#153](https://github.com/Altinn/team-core-private/issues/153) (team-core-private)
> Remove redundant build action for Sonar caching

- src/Altinn.Notifications.Core/Models/Notification/SmsSendOperationResult.cs
- src/Altinn.Notifications.Core/Persistence/ISmsNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Persistence/Repository/SmsNotificationRepository.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/SmsStatusConsumerTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/SmsSendOperationResultTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
The primary objective was to rename data members to more accurately reflect their purpose. However, this seemingly minor change could require updates to various parts of the service and potentially disrupt implementations for other users. So we simply revert them.
- #700
> Revert changes made on the data model

- src/Altinn.Notifications/Controllers/OrdersController.cs
- src/Altinn.Notifications/Controllers/SmsNotificationOrdersController.cs
- src/Altinn.Notifications/Program.cs
Adds a definition of the Bearer authentication `security` scheme to the OpenAPI document, and applies it on the operation level. That is, each endpoint (that has an `[Authorize(..)]` tag in action/controller) gets marked with a `security` attribute in the Swagger doc, indicating how that endpoint is protected.
This is implemented by extending the SwaggerGen options in application startup (Program.cs), through the addition of the (bearer) security definition and the `OperationFilter<SecurityRequirementsOperationFilter>`.
- [#168](https://github.com/orgs/Altinn/projects/20/views/11?pane=issue&itemId=98905829&issue=Altinn%7Cteam-core-private%7C168) (team-core-private)
> Add security def and requirement to swaggergen-options

- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
Filters out the Npgsql-spawned 'received-first-response' records in the trace log
- N/A
> Ignore the first response event in tracing

- src/Altinn.Notifications.Core/Models/Orders/NotificationOrderChainRequest.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications.Persistence/Repository/OrderRepository.cs
- src/Altinn.Notifications/Mappers/NotificationOrderChainMapper.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/OrderRepositoryTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/NotificationOrderChainMapperTests.cs
The `ORDERID` field in the `ORDERSCHAIN` table is currently pointing to the main notification row in the `ORDERS` table. This causes `notificationOrderId` and `shipmentId` in the API response to have the same value for the main notification, potentially leading to confusion.
- #768
> Ensure `ORDERID` field in the `ORDERSCHAIN` table uniquely identifies the order chain
