- .dockerignore
- .github/reusables/build-image.yaml
- .github/workflows/build-notifications.yml
- Dockerfile
Add Dockerfile and extend actions to build image and push to ghcr.io
> Build dockerimage

- src/Altinn.Notifications.Core/NotificationsService.cs
- test/Altinn.Notifications.Tests/IntegrationTests/NotificationApiTests.cs
- test/Altinn.Notifications.Tests/Mocks/NotificationRepositoryMock.cs
> bugfix: set target and msg on response obj

- .editorconfig
- src/Altinn.Notifications.Core/INotifications.cs
- src/Altinn.Notifications.Core/INotificationsRepository.cs
- src/Altinn.Notifications.Core/NotificationsService.cs
- src/Altinn.Notifications.Integrations/Configuration/SmtpSettings.cs
- src/Altinn.Notifications.Persistence/DataReaderExtensions.cs
- src/Altinn.Notifications.Persistence/NotificationRepository.cs
- src/Altinn.Notifications/Altinn.Notifications.csproj
- src/Altinn.Notifications/Controllers/NotificationsController.cs
- src/Altinn.Notifications/Controllers/OutboundController.cs
- src/Altinn.Notifications/Controllers/SendController.cs
- src/Altinn.Notifications/Services/UserTokenProvider.cs
- test/Altinn.Notifications.Tests/IntegrationTests/NotificationApiTests.cs
- test/Altinn.Notifications.Tests/IntegrationTests/OutboundApiTests.cs
- test/Altinn.Notifications.Tests/Mocks/NotificationRepositoryMock.cs
- test/Altinn.Notifications.Tests/Persistence/NotificationRepositoryTests.cs
Fixed a few code smells. In many cases related to null references the changes simply moves the issue to other method calls, but it is a step in the right direction.
> Some code smells removed, other simply moved.

- .github/workflows/build-deploy-main.yml
- .github/workflows/build-deploy-release.yml
- .github/workflows/deploy-image.yaml
ref:
https://github.community/t/reusable-workflows-secrets-and-environments/203695/39
> secrets needs to be explicitly named for them to be accessible

- .editorconfig
- src/Altinn.Notifications.Core/Models/Target.cs
- src/Altinn.Notifications.Functions/Integrations/INotifications.cs
- src/Altinn.Notifications.Functions/Integrations/IToken.cs
- src/Altinn.Notifications.Functions/Integrations/QueueService.cs
- src/Altinn.Notifications.Functions/Integrations/ScheduleService.cs
- src/Altinn.Notifications.Functions/ScheduleEMail/ScheduleEMail.cs
- src/Altinn.Notifications.Functions/ScheduleSMS/ScheduleSMS.cs
- src/Altinn.Notifications.Functions/Send/Send.cs
- src/Altinn.Notifications.Functions/Startup.cs
- src/Altinn.Notifications.Interfaces/Models/TargetExt.cs
- src/Altinn.Notifications.Persistence/PostgreSQLSettings.cs
- src/Altinn.Notifications/Controllers/NotificationsController.cs
- test/Altinn.Notifications.Tests/Mocks/NotificationRepositoryMock.cs
- test/Altinn.Notifications.Tests/UnitTests/Integrations/ProfileClientTests.cs
Added naming rule for fields. Fields should begin with _.
Removed all unused usings.
> Random fixes

- src/Altinn.Notifications.Functions/Integrations/KeyVaultService.cs
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- src/Altinn.Notifications/Altinn.Notifications.csproj
- src/Altinn.Notifications/Program.cs
> replaced deprecated packs

- Dockerfile
- src/Altinn.Notifications.Core/Altinn.Notifications.Core.csproj
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
> patching w24

- src/Altinn.Notifications/Program.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Core/Consumers/PastDueOrdersConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/KafkaUtil.cs
- test/Altinn.Notifications.IntegrationTests/Utils/PostgreUtil.cs
- test/Altinn.Notifications.IntegrationTests/Utils/ServiceUtil.cs
> made utils for common test functionality

- src/Altinn.Notifications.Integrations/Altinn.Notifications.Integrations.csproj
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Health/KafkaHealthCheck.cs
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Persistence/Health/PostgresHealthCheck.cs
- src/Altinn.Notifications/Program.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/KafkaHealthCheckTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/PostgresHealthCheckTests.cs
> Fixed failing health checks

- src/Altinn.Notifications.Core/Models/Email.cs
- src/Altinn.Notifications.Core/Services/EmailNotificationService.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/EmailTests.cs
Ensuring we have the correct serializer for email and that enums are serialized as string
- N/A
> custom serializer for email model

- .github/workflows/build-and-analyze.yml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/.gitignore
- test/k6/docker-compose.yml
- test/k6/readme.md
- test/k6/src/api/notifications.js
- test/k6/src/api/token-generator.js
- test/k6/src/apiHelpers.js
- test/k6/src/config.js
- test/k6/src/data/orders/01-email-request.json
- test/k6/src/errorhandler.js
- test/k6/src/report.js
- test/k6/src/reports/readme.md
- test/k6/src/setup.js
- test/k6/src/tests/orders_email.js
- k6 tests for get endpoints
- setup for automated tests for at and tt
- #197
> Automated k6 tests and workflow

- src/Altinn.Notifications.Integrations/Kafka/SharedClientConfig.cs
Workaround until kafka on confluent if completely configured
> no sasl for dev or staging

- src/Altinn.Notifications.Integrations/Configuration/KafkaSettings.cs
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/PastDueOrdersConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/PastDueOrdersRetryConsumer.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/IntegrationTestWebApplicationFactory.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerRetryTests.cs
- test/Altinn.Notifications.IntegrationTests/appsettings.IntegrationTest.json
Renamed a config variable and related classes e.g. PastDueOrdersTopicNameRetry = >PastDueOrdersRetryTopicName
> PastDueOrdersTopicNameRetry -> PastDueOrdersRetryTopicName

- src/Altinn.Notifications.Integrations/Kafka/SharedClientConfig.cs
- test/Altinn.Notifications.IntegrationTests/IntegrationTestWebApplicationFactory.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/KafkaHealthCheckTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerRetryTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/TestdataUtil.cs
- test/Altinn.Notifications.IntegrationTests/appsettings.IntegrationTest.json
- test/Altinn.Notifications.Tests/Notifications.Integrations/SharedClientConfigTests.cs
Changed implementation of shared client config to not depend on environment
> set client config based on presence of username and pw

- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/PastDueOrdersConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/PastDueOrdersRetryConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Producers/KafkaProducer.cs
> ensure exception does not exit while loop

- src/Altinn.Notifications.Integrations/Configuration/KafkaSettings.cs
- src/Altinn.Notifications.Integrations/Health/KafkaHealthCheck.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
- src/Altinn.Notifications.Integrations/Kafka/Producers/KafkaProducer.cs
- src/Altinn.Notifications.Integrations/Kafka/SharedClientConfig.cs
- src/Altinn.Notifications/Program.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/KafkaHealthCheckTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerRetryTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_PastDueOrdersTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_SendEmailNotificationsTests.cs
- test/Altinn.Notifications.IntegrationTests/appsettings.IntegrationTest.json
- test/Altinn.Notifications.Tests/Notifications.Integrations/SharedClientConfigTests.cs
- test/Altinn.Notifications.Tests/appsettings.Test.json
> seperate sasl for all clients

- src/Altinn.Notifications/appsettings.json
Consistent naming of all topics
> Consistent topic naming

- src/Altinn.Notifications.Core/Models/Email.cs
- src/Altinn.Notifications.Core/Services/EmailNotificationService.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/EmailTests.cs
renamed id property for clarity
> id -> notificationId on email object

- src/Altinn.Notifications/Validators/EmailNotificationOrderRequestValidator.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
- test/k6/docker-compose.yml
- test/k6/src/data/orders/01-email-request.json
minor fixes
- patching
- spelling
> minor code fixes

- src/Altinn.Notifications.Core/Enums/EmailNotificationResultType.cs
- src/Altinn.Notifications.Core/Models/Email.cs
- src/Altinn.Notifications.Core/Models/Notification/SendOperationResult.cs
- src/Altinn.Notifications.Core/Repository/Interfaces/IEmailNotificationRepository.cs
- src/Altinn.Notifications.Core/Services/EmailNotificationService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IEmailNotificationService.cs
- src/Altinn.Notifications.Integrations/Configuration/KafkaSettings.cs
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/EmailStatusConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
- src/Altinn.Notifications.Persistence/Migration/v0.06/01-alter-tables.sql
- src/Altinn.Notifications.Persistence/Migration/v0.06/02-setup-procedures.sql
- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/IntegrationTestWebApplicationFactory.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/EmailStatusConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/PostgreUtil.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/EmailNotificationServiceTests.cs
> Status-message consumer

- src/Altinn.Notifications/appsettings.json
> Fix topic name

- src/Altinn.Notifications.Integrations/Kafka/Producers/KafkaProducer.cs
> log error in case of producer exception

- src/Altinn.Notifications/appsettings.json
Application throws exception when consumer cannot connect to topic. 
We should ensure that all topics we interact with exists on startup. 
N/A
> added missing topic in topic list

- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
Ensure message is populated for use in retry method 
- #166
> Bugfix in kafka consumer for retry logic

- src/Altinn.Notifications.Persistence/Migration/v0.08/01-setup-functions.sql
Add 30 sec grace period for retrieving past due orders
- #262
> added 30 sec graceperiod

- src/Altinn.Notifications.Core/Services/OrderProcessingService.cs
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- src/Altinn.Notifications.Persistence/Repository/EmailNotificationRepository.cs
- src/Altinn.Notifications.Persistence/Repository/OrderRepository.cs
- src/Altinn.Notifications.Persistence/Repository/TelemetryTracker.cs
- src/Altinn.Notifications/Altinn.Notifications.csproj
- Let npgsql do json convertion for notificationorder
- Added dependency tracking for postgres
- Added loop in StartProcessingPastDueOrders
- (One commit for each)
- #{253}
> DB tuning: json convertion and dependency tracking for postgres

- src/Altinn.Notifications.Core/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/EmailStatusConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/PastDueOrdersRetryConsumer.cs
- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Persistence/Extensions/WebApplicationExtensions.cs
Fixed messages and removed unused references
> cosmetic code changes

- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications/Configuration/AuthorizationConstants.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/PostTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetByIdTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetBySendersRefTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetWithStatusById.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/OrdersControllerTests.cs
- test/k6/src/tests/orders_email.js
altinn:notifications.create -> altinn:serviceowner/notifications.create
> notifications.create part of serviceowner scopes

- src/Altinn.Notifications.Persistence/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Persistence/Health/PostgresHealthCheck.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/PostgresHealthCheckTests.cs
- test/Altinn.Notifications.Tests/Notifications.Persistence/TestingExtensions/ServiceCollectionExtensionsTests.cs
- shared data source for health check and repositories
- made test classes disposable instead of the health check class 
- 
- #N/A
> Shared data source for health check and repository

- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/src/api/authentication.js
- test/k6/src/api/maskinporten.js
- test/k6/src/apiHelpers.js
- test/k6/src/config.js
- test/k6/src/setup.js
- test/k6/src/tests/orders_email.js
- prod use case workflow
- maskinporten support in k6
- #266
> added maskinporten support to k6 tests

- src/Altinn.Notifications/Program.cs
Removed health checks for now. 
- #268
> removed health checks

- src/Altinn.Notifications.Core/Services/OrderProcessingService.cs
- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- src/Altinn.Notifications/Controllers/OrdersController.cs
- src/Altinn.Notifications/Extensions/ResourceLinkExtensions.cs
- src/Altinn.Notifications/Mappers/OrderMapper.cs
- src/Altinn.Notifications/Models/EmailContentTypeExt.cs
- src/Altinn.Notifications/Models/EmailNotificationOrderRequestExt.cs
- src/Altinn.Notifications/Models/EmailTemplateExt.cs
- src/Altinn.Notifications/Models/IBaseNotificationOrderExt.cs
- src/Altinn.Notifications/Models/NotificationChannelExt.cs
- src/Altinn.Notifications/Models/NotificationOrderExt.cs
- src/Altinn.Notifications/Models/NotificationOrderWithStatusExt.cs
- src/Altinn.Notifications/Models/OrderIdExt.cs
- src/Altinn.Notifications/Models/RecipientExt.cs
- src/Altinn.Notifications/Program.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/PostTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetByIdTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetWithStatusById.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
Found a few things to change in the external models. 2 internal enums were exposed
- #295
> Fixes to external models

- src/Altinn.Notifications.Core/Enums/EmailNotificationResultType.cs
- src/Altinn.Notifications.Persistence/Migration/v0.10/01-alter-enum.sql
- Altinn/altinn-notifications-email#25
> New send-status for invalid email format

- src/Altinn.Notifications/Validators/EmailNotificationOrderRequestValidator.cs
- test/Altinn.Notifications.Tests/Notifications/TestingValidators/EmailNotificationOrderRequestValidatorTests.cs
Added validation of email address format to the order request validator
- N/A
> added validation of email addresses #GCPActive

- setup-kafka.yml
Bugfix for failing config after kafdrop upgrade
> removed Xss180Kseting for kafdrop #GCPActive

- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
Bug fix for error message in use case workflows
> Fixed use case error message in workflow

- test/k6/src/config.js
> added missing baseurl for prod

- src/Altinn.Notifications.Persistence/Migration/v0.14/01-alter-function.sql
> fix sql for retrieving new emails to respect timeout

- .github/workflows/build-and-analyze.yml
> using sonar.token instead of login

- .github/workflows/regression-test-AT23.yaml
- .github/workflows/regression-test-AT24.yaml
> Specify job names

- src/Altinn.Notifications.Persistence/Migration/v0.16/01-setup-types.sql
- src/Altinn.Notifications.Persistence/Migration/v0.16/02-setup-table.sql
> Add new table, smsnotifications

- src/Altinn.Notifications/Controllers/TriggerController.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_SendEmailNotificationsTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_SendSmsNotificationsTests.cs
Trigger endpoint added for starting process of sending sms 
- #350
> #350 Added sms endpoint to trigger controller #GCPActive

- src/Altinn.Notifications.Core/Configuration/KafkaSettings.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Integrations/Kafka/Producers/KafkaProducer.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_SendSmsNotificationsTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
> fixed settings name

- src/Altinn.Notifications.Core/Models/Notification/EmailSendOperationResult.cs
- src/Altinn.Notifications.Core/Models/Notification/SmsSendOperationResult.cs
- src/Altinn.Notifications.Core/Services/EmailNotificationService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/IEmailNotificationService.cs
- src/Altinn.Notifications.Core/Services/Interfaces/ISmsNotificationService.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationService.cs
- src/Altinn.Notifications.Integrations/Configuration/KafkaSettings.cs
- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/EmailStatusConsumer.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/SmsStatusConsumer.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/SmsStatusConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsController/GetTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/EmailNotificationServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationServiceTests.cs
> Consumer and service for update status sms

- src/Altinn.Notifications/Mappers/OrderMapper.cs
- src/Altinn.Notifications/Models/NotificationOrderExt.cs
- src/Altinn.Notifications/Models/SmsTemplateExt.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
> Extended notificationOrderExt with sms properties

- src/Altinn.Notifications/Models/SmsTemplateExt.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/TestingConsumers/PastDueOrdersRetryConsumerTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Persistence/SmsNotificationRepositoryTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsController/GetTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetByIdTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetBySendersRefTests.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/OrdersController/GetWithStatusById.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/TriggerController/Trigger_PastDueOrdersTests.cs
- test/Altinn.Notifications.IntegrationTests/Utils/PostgreUtil.cs
- test/Altinn.Notifications.IntegrationTests/Utils/TestdataUtil.cs
- Ensure default sms sender is defined in appsettings
- Added seperate metod for populating db with sms order
- Removed internal set for Ext model
- N/A
> various bug fixes

- src/Altinn.Notifications/Altinn.Notifications.csproj
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
Patched library with bug fix for excessive logging. 
- N/A
> Patched Altinn.Common.AccessToken dependency

- test/Altinn.Notifications.IntegrationTests/Altinn.Notifications.IntegrationTests.csproj
- test/Altinn.Notifications.Tests/Altinn.Notifications.Tests.csproj
Patching of package dependencies
> patching w6

- test/k6/src/data/orders/02-sms-request.json
- test/k6/src/tests/orders_sms.js
Varying the content of the SMS during our automated tests
> partly random content for sms in k6 test #GCPActive

- src/Altinn.Notifications.Persistence/Migration/v0.22/01-setup-indexes.sql
Added indexes to support our current queries. 
- #422
> added indexes for orders and sms tables

- test/k6/src/tests/orders_sms.js
Automated tests for new sms notification summary endpoint
Can be merged when #418 is deployed to TT
- #428
> k6 tests for sms summary

- src/Altinn.Notifications.Core/Enums/SmsNotificationResultType.cs
- src/Altinn.Notifications.Core/Services/SmsNotificationSummaryService.cs
- src/Altinn.Notifications.Persistence/Migration/v0.23/00-drop-functions.sql
- src/Altinn.Notifications.Persistence/Migration/v0.23/01-alter-types.sql
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/SmsNotificationSummaryServiceTests.cs
We have extended the sms status codes with the ones we get in the delivery report. 
- #361
- #427
> New status codes for SMS

- .github/workflows/regression-test-PROD.yaml
- .github/workflows/use-case-PROD.yaml
Production test workflows now include step for sms
> added sms tasks for prod workflows

- test/Altinn.Notifications.Tests/Notifications.Core/TestingModels/EmailSendOperationResultTests.cs
> Add tests for EmailSendOperationResult

- src/Altinn.Notifications/Controllers/SmsNotificationOrdersController.cs
- src/Altinn.Notifications/appsettings.json
- test/Altinn.Notifications.IntegrationTests/Notifications/SmsNotificationsOrdersController/SmsNotificationOrdersControllerTests.cs
> return accepted when lookup fails

- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications/Controllers/EmailNotificationOrdersController.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/EmailNotificationsOrderController/EmailNotificationOrdersControllerTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
> ensure failed lookup requests are persisted too

- src/Altinn.Notifications/Mappers/OrderMapper.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/OrderMapperTests.cs
> Fixed bug. Now mapping ignoreReservations to api model

- test/Altinn.Notifications.IntegrationTests/appsettings.IntegrationTest.json
Tests fail due to connection limit in db. Testing to reduce idle time to 10 sec
> idle time 10 sec for int tests

- src/Altinn.Notifications.Core/Services/ContactPointService.cs
> ensure null does not give address point

- .github/workflows/regression-test-ATX.yml
- .github/workflows/regression-test-PROD.yaml
- .github/workflows/regression-test-TT02.yaml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/src/tests/orders_email.js
Added nin lookup to email automated test 
- #441
> added nin lookup k6 test

- src/Altinn.Notifications.Core/Helpers/MobileNumberHelper.cs
> handling empty mobile no in validation

- src/Altinn.Notifications.Core/Services/AltinnServiceUpdateService.cs
- src/Altinn.Notifications.Core/Services/NotificationsEmailServiceUpdateService.cs
- src/Altinn.Notifications.Integrations/Kafka/Consumers/KafkaConsumerBase.cs
- src/Altinn.Notifications.Integrations/Kafka/Producers/KafkaProducer.cs
- src/Altinn.Notifications/Program.cs
- test/Altinn.Notifications.IntegrationTests/Notifications.Integrations/KafkaHealthCheckTests.cs
> fixed code smells

- README.md
- src/Altinn.Notifications.Persistence/Altinn.Notifications.Persistence.csproj
- test/k6/readme.md
- Updated readme to match reality.
- Ensured podman compose runs ok locally
> Readme up to date

- .github/workflows/regression-test-ATX.yml
- .github/workflows/regression-test-PROD.yaml
- .github/workflows/regression-test-TT02.yaml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/src/tests/orders_email.js
- test/k6/src/tests/orders_org_no.js
#510 Implementation of adding regression and use case tests that include an app affiliation
#510 Implementation of adding regression and use case tests that include an app affiliation
- #510
- #507
> #510 Implementation of adding regression and use case tests that include an app affiliation

- .github/workflows/use-case-ATX.yaml
> #510 Fix: Removed use case quote string

- Dockerfile
- src/Altinn.Notifications.Core/Services/NotificationScheduleService.cs
Time zone info is missing from Docker image, adding tzdata package to fix the issue.
- #538
> added tzdata package to docker image

- .github/workflows/regression-test-ATX.yml
- .github/workflows/regression-test-PROD.yaml
- .github/workflows/regression-test-TT02.yaml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/src/tests/orders_org_no.js
#510 Re-reverting #510 commit as new email address added (#558)
#510 Re-reverting #510 commit as new email address added (#558)
- #558 
- #510
> #510 Re-reverting #510 commit as new email address added (#558)

- .github/workflows/regression-test-ATX.yml
- .github/workflows/regression-test-PROD.yaml
- .github/workflows/regression-test-TT02.yaml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
- test/k6/src/api/notifications/notifications.js
- test/k6/src/api/notifications/orders.js
- test/k6/src/config.js
- test/k6/src/data/orders/01-email-request.json
- test/k6/src/tests/orders_email.js
Expand the automated tests to include condition checks when making an email notification order.
- #549 
- #562
> Add condition checks to tests

- src/Altinn.Notifications/Extensions/UriExtensions.cs
Ensuring an invalid uri does not result in exception during validation.
- #571
> ensure uri can be created from string before validation

- .github/workflows/build-and-analyze.yml
Made test results available as an artifact as part of workflow run. 
- #594
> Make test report downloadable after workflow run 

- .github/workflows/build-and-analyze.yml
- test/Altinn.Notifications.Tests/Notifications/TestingExtensions/StringExtensionsTests.cs
> Add dummy test to check failing workflow

- src/Altinn.Notifications.Integrations/Altinn.Notifications.Integrations.csproj
- src/Altinn.Notifications/Altinn.Notifications.csproj
Update Altinn.ApiClients.Maskinporten to new version.
> Update apiclients maskinporten

- src/Altinn.Notifications.Integrations/Extensions/ServiceCollectionExtensions.cs
- src/Altinn.Notifications.Integrations/Register/RegisterClient.cs
Use JsonContent instead of StringContent to simplify the code and make it more concise.
- #688
> Use JsonContent instead of StringContent

- .github/workflows/regression-test-ATX.yml
- .github/workflows/regression-test-PROD.yaml
- .github/workflows/regression-test-TT02.yaml
- .github/workflows/use-case-ATX.yaml
- .github/workflows/use-case-PROD.yaml
- .github/workflows/use-case-TT02.yaml
Follow recommendations from docs for Slack github action v2, to adjust to breaking changes
- [# 132 (team-core-private)](https://github.com/Altinn/team-core-private/issues/132)
> Fix job that reports failed tests to Slack

- test/k6/src/tests/orders_org_no.js
Add a k6 tests for issue previosly merged https://github.com/Altinn/altinn-notifications/pull/706
- #{issue number}
> Add a use case test for smsOrder with orgNo

- Dockerfile
Remediate [CVE-2025-24070](https://avd.aquasec.com/nvd/2025/cve-2025-24070/)
- N/A
> Bump mcr.microsoft.com/dotnet/aspnet v9.0.2 -> 9.0.3

- src/Altinn.Notifications.Core/Models/Orders/NotificationOrderChainResponse.cs
- src/Altinn.Notifications.Core/Services/OrderRequestService.cs
- src/Altinn.Notifications/Controllers/FutureOrdersController.cs
- src/Altinn.Notifications/Mappers/NotificationOrderChainResponseMapper.cs
- src/Altinn.Notifications/Models/NotificationOrderChainResponseExt.cs
- test/Altinn.Notifications.IntegrationTests/Notifications/FutureOrdersController/FutureOrdersControllerTests.cs
- test/Altinn.Notifications.Tests/Notifications.Core/TestingServices/OrderRequestServiceTests.cs
- test/Altinn.Notifications.Tests/Notifications/TestingMappers/NotificationOrderChainResponseMapperTests.cs
The response should show unique identifier to the main order chain and each single order in that chain.
- #775
> Make sure the order identifier is not equal to the order chain identifier

- src/Altinn.Notifications.Persistence/Repository/NotificationRepositoryBase.cs
Log more information to help investigate the issue
- #980
> Log more information
